name: userapp
description: Mikro mart user application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+23

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.3
  get_it: ^1.0.3+2
  rxdart: ^0.21.0
  flutter_swiper: ^1.1.6
  flip_card: ^0.2.1
  fancy_bottom_navigation: ^0.3.2
  smooth_star_rating: ^1.0.3
  carousel_slider: 2.2.1
  flare_flutter: ^1.5.5
  dartz: ^0.8.8
  basic_utils: ^1.3.0
  url_launcher: 5.5.0
  cupertino_icons: ^0.1.2
  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_analytics: ^5.0.2
  firebase_messaging: ^6.0.16
  google_sign_in: 4.5.1
  intl: 0.16.1
  algolia: 0.1.7
  flutter_spinkit:
  flutter_staggered_grid_view:
  location_permissions: ^3.0.0
  launch_review: ^1.0.1

  flushbar: 1.10.4
  package_info: 0.4.3

  # Address
  google_maps_flutter: 0.5.28+1

  geolocator: ^5.3.2+2

  # Moor
  moor_flutter:
  fluro: "^1.3.1"

  # Local cache
  shared_preferences: ^0.5.4+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.7.5
  moor_generator:
  build_runner:

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: CustomSocial
      fonts:
        - asset: assets/CustomSocial.ttf
    - family: Timesroman
      fonts:
        - asset: assets/serif-regular.ttf
        - asset: assets/serifbold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: assets/Quicksand-Regular.ttf
  assets:
      - assets/home_background.jpeg

      - assets/logo.png
      - assets/white_logo.png

      - assets/otp1.png
      - assets/logo_banner.png

      - assets/tick.png
      - assets/empty.flr

      - assets/next.png
