name: userapp
description: Mikro mart user application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0+1
  get_it: ^1.0.3+2
  rxdart: ^0.21.0
  flutter_swiper: ^1.1.6
  flip_card: ^0.2.1
  fancy_bottom_navigation: ^0.3.2
  smooth_star_rating: ^1.0.3
  carousel_slider: ^1.3.0
  flare_flutter: ^1.5.5

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  image_path: "assets/icons&splashs/Asset 41.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: CustomSocial
      fonts:
        - asset: assets/CustomSocial.ttf
    - family: Timesroman
      fonts:
        - asset: assets/serif-regular.ttf
        - asset: assets/serifbold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: assets/Quicksand-Regular.ttf
  assets:
      - assets/home_background.jpeg
      - assets/food1.jpg
      - assets/food2.jpg
      - assets/food3.jpg
      - assets/food4.jpg
      - assets/food5.jpg
      - assets/food6.jpg
      - assets/food7.jpg
      - assets/food8.jpg
      - assets/food9.jpg
      - assets/food10.jpg
      - assets/food11.jpg
      - assets/food12.jpg
      - assets/food13.jpg
      - assets/food14.jpg
      - assets/profil.jpg
      - assets/profile2.jpg
      - assets/profile3.jpg
      - assets/profil4.jpg
      - assets/sun.png
      - assets/moon.png
      - assets/switcher.flr
      - assets/Walkthrough/Best_Chef_day.png
      - assets/Walkthrough/Best_Chef_night.png
      - assets/Walkthrough/Perfect_Price_day.png
      - assets/Walkthrough/Perfect_Price_night.png
      - assets/Walkthrough/Perfect_Taste_day.png
      - assets/Walkthrough/Perfect_Taste_night.png
      - assets/Walkthrough/Relaxed_Atmosphere_day.png
      - assets/Walkthrough/Relaxed_Atmosphere_night.png
      - assets/Walkthrough/transparent.png
      - assets/icons&splashs/splash_day.png
      - assets/icons&splashs/splash_night.png
      - assets/icons&splashs/Asset 61.png
      - assets/icons&splashs/Asset 51.png
      - assets/icons&splashs/Asset 41.png
      - assets/icons&splashs/Asset 31.png
      - assets/Walkthrough/
      - assets/icons&splashs/