name: userapp
description: Mikro mart user application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+30

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.3
  get_it: ^1.0.3+2
  rxdart: ^0.21.0
  flutter_swiper: ^1.1.6
  flip_card: ^0.2.1
  fancy_bottom_navigation: ^0.3.2
  curved_navigation_bar:
  smooth_star_rating: ^1.0.3
  carousel_slider: 3.0.0
  flare_flutter: ^1.5.5
  dartz: ^0.8.8
  http: ^0.12.2
  basic_utils: ^1.3.0
  url_launcher: 5.5.0
  cupertino_icons: ^0.1.2
  cached_network_image:
  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_analytics:
  firebase_messaging:
  google_sign_in:
  intl: 0.16.1
  algolia: 0.1.7
  razorpay_flutter:
    git:
      url: git://github.com/razorpay/razorpay-flutter.git
      ref: master
  flutter_spinkit:
  flutter_staggered_grid_view:
  location_permissions: ^3.0.0
  launch_review: ^1.0.1
  pin_code_fields:
  flushbar: 1.10.4
  package_info: 0.4.3

  # Address
  google_maps_flutter: 0.5.28+1

  geolocator: ^5.3.2+2

  # Moor
  moor_flutter:
  fluro: "^1.3.1"

  # Local cache
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.7.5
  moor_generator:
  build_runner:

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: CustomSocial
      fonts:
        - asset: assets/CustomSocial.ttf
    - family: Timesroman
      fonts:
        - asset: assets/serif-regular.ttf
        - asset: assets/serifbold.ttf
          weight: 700

    - family: Quicksand
      fonts:
        - asset: assets/Quicksand-Regular.ttf

    - family: Mulish
      fonts:
         - asset: assets/mulish_bold.ttf
         - asset: assets/mulish_semibold.ttf
         - asset: assets/mulish_regular.ttf

  assets:
      - assets/home_background.jpeg

      - assets/logo.png
      - assets/white_logo.png
      - assets/dot_big.png
      - assets/dot_small.png
      - assets/basket.png
      - assets/flag_bg.png
      - assets/map.png
      - assets/item_unavailable_bg.png
      - assets/purchase_success.png
      - assets/splash_image.png
      - assets/mikromart_category.jpg

      - assets/otp1.png
      - assets/logo_banner.png

      - assets/tick.png
      - assets/empty.flr

      - assets/next.png
